### ISSUE TITLE
Add --no-verify-ssl capability

### ISSUE THREAD

**Issue by AntonFriberg** [peakgames/s5cmd#11]
Hi!

During testing of self hosted s3 storage solutions it is vital to be able to turn off the ssl verification. This functionality is supported by the awscli client with the `--no-verify-ssl` flag.

It seems the aws-sdk-go has the functionality needed:
https://github.com/aws/aws-sdk-go/issues/2404

**Comment by ilkinulas** [comment]
Thank you very much for this feature request. It'll be a great addition to the current feature set.
