### ISSUE TITLE
Use with S3-compatible service

### ISSUE THREAD

**Issue by arl** [peakgames/s5cmd#4]
Hi,
Can't seem to find a way to set the URL in order to use with a S3-compatible service/server that is not aws.
If there isn't any way to do that with, for example, a command line flag, would you consider a pull request implementing that feature?

**Comment by igungor** [comment]
Hi,

That'd be very nice actually. PR is always welcome.

**Comment by arl** [comment]
Ok, but shouldn't it be possible to directly use `.aws/config` with `AWS_SDK_LOAD_CONFIG=1` ? Couldn't make it work though.

**Comment by arl** [comment]
Hi
I was under the impression, incorrectly, that `.aws/config` could be used for specifying any field of the `aws.Config` structure, so that adding command line flags for `endpoint` to s5cmd was useless because it could be more easily done from `.aws/config`. But it seems this file only supports 3 or 4 fields like region, etc.

The use case is the following: a company where I worked would like to use s5cmd for performance of their S3-compatible cloud storage service, obviously hosted at another address. It seems the only way will be to add those cli flags then!
