### ISSUE TITLE
missing build instructions / binary releases

### ISSUE THREAD

**Issue by innovia** [peakgames/s5cmd#6]
please provide some instructions on how to build this on linux - even after setting up go path and trying go build . its not installaing a binary - or just supply a binary via releases

**Comment by aykutfarsak** [comment]
Hi @innovia, you can run `make` command on project root directory (`{GOPATH}/src/github.com/peakgames/s5cmd`) to build the binary.

Also, we will provide extra instructions about building as you suggested, thanks 👍

**Comment by innovia** [comment]
my mistake, I've used 1.7.4 which is the distro version

This is how i solved it

``` 
docker run -it debian:stretch bash
apt-get update && apt-get install wget  git -y
wget https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
tar -xvf go1.10.3.linux-amd64.tar.gz
mv go /usr/local
export GOROOT=/usr/local/go
export GOPATH=/root/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

$ go version
go version go1.10.3 linux/amd64


go get -u github.com/peakgames/s5cmd

$ s5cmd -version
s5cmd version v0.6.0
```

And for the local build:
```
apt-get install build-essential -y
cd ${GOPATH}/src/github.com/peakgames/s5cmd
$ make
find . ! -path "*/vendor/*" -type f -name '*.go' -exec /usr/local/go/bin/gofmt -l -s -w {} \;
/usr/local/go/bin/go build  -ldflags "" .
```
**the only thing that is missing in the make:**
`go install `
