### ISSUE TITLE
cp command flattens directory structure

### ISSUE THREAD

**Issue by ojotoxy** [peakgames/s5cmd#8]

**Comment by ilkinulas** [comment]
@ojotoxy did you try `cp` command with the `--parents` option.

> --parents  Create directory structure in destination, starting from the first wildcard

Is that what you want?

**Comment by ojotoxy** [comment]
Cool, I missed that option! Sent a PR making it more clear. Thank you!

**Comment by innerlee** [comment]
Bitten by this. Wasted 2 days of uploading work. :(
